export const USER_REPOSITORY_NAME = 'USER_REPOSITORY_NAME';
export const COMPANY_REPOSITORY_NAME = 'COMPANY_REPOSITORY_NAME';
export const USER_PERMISSION_REPOSITORY_NAME =
  'USER_PERMISSION_REPOSITORY_NAME';
export const MONEY_TRANFERS_REPOSITORY_NAME = 'MONEY_TRANFERS_REPOSITORY_NAME';
